[accessLog]
format = "json"

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]
      certResolver = "myresolver"

[certificatesResolvers.myresolver.acme]
  email = "hscrystaleng@gmail.com"
  storage = "acme.json"
  [certificatesResolvers.myresolver.acme.tlsChallenge]

[api]

[providers]
  [docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false
  [file]
    directory = /rule/